<?php
/**
 * @category    Inchoo
 * @package     RiafyNew_ModalOverlay
 * @copyright   Copyright (c) Inchoo (https://inchoo.net/)
 */
?>
<?php /** @var Inchoo\ModalOverlay\Block\ModalOverlay $block */ ?>
<div id="modal-overlay" style="display:none;">
test
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "modal_overlay": {
                        "component": "RiafyNew_ModalOverlay/js/modal_overlay"
                    }
                 }
            }
        }
    }
</script>